"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "./components/AppSidebar";
import { Header } from "./components/Header";
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";
import { First } from "./components/First";
import { AppProvider } from "./context/AppContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <SignedOut>
            <First />
          </SignedOut>
          <SignedIn>
            <SidebarProvider defaultOpen={false}>
              <div className="flex flex-col h-screen">
                <header className="h-14">
                  <Header />
                </header>
                <div className="flex flex-1 overflow-hidden ">
                  <AppProvider>
                    <AppSidebar />
                    <main className="flex overflow-y-auto ">
                      <div className="h-full w-18 border border-[#E4E4E7] flex justify-center">
                        <SidebarTrigger className="h-10 w-10" />
                      </div>{" "}
                      {children}
                    </main>
                  </AppProvider>
                </div>
              </div>
            </SidebarProvider>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
